services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      ALIGNMENT: "left"
      FOOTER_TEXT: "Powered by <a href='https://github.com/knsrinath/easyserve'>EasyServe</a>"
      COLOR_PALETTE: "solarized"
      THEME: "dark"
    volumes:
      - ./files:/var/www/html/files
